<!DOCTYPE BOOKS [
<!ELEMENT BOOKS (BOOK)+>
<!ELEMENT BOOK (TITLE,(AUTHOR|AUTHORS))>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT AUTHOR (FIRSTNAME,LASTNAME)>
<!ELEMENT FIRSTNAME (#PCDATA)>
<!ELEMENT LASTNAME (#PCDATA)>
<!ELEMENT AUTHORS (NAME)+>
<!ELEMENT NAME (#PCDATA)>
]>
<BOOKS>
	<BOOK>
		<TITLE>You can win</TITLE>
		<AUTHOR>
			<FIRSTNAME>Shiv</FIRSTNAME>
			<LASTNAME>Khera</LASTNAME>
		</AUTHOR>
	</BOOK>
	<BOOK>
		<TITLE>Let us C</TITLE>
		<AUTHORS>
			<NAME>Balagurusamy</NAME>
			<NAME>Jagadeeswaran</NAME>
		</AUTHORS>
	</BOOK>
</BOOKS>
