<!DOCTYPE PRODUCTS [
<!ELEMENT PRODUCTS (PRODUCT)+>
<!ELEMENT PRODUCT (NAME,DESCRIPTION,PRICE)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT PRICE (#PCDATA)>
<!ATTLIST PRODUCT PID ID #REQUIRED
	CATEGORY CDATA #REQUIRED	
>
]>

<PRODUCTS>
	<PRODUCT PID="P001" CATEGORY="Electronics">
		<NAME>Computer</NAME>
		<DESCRIPTION>Computer brand  5th Generation Legion Processor is I7</DESCRIPTION>
		<PRICE>130000</PRICE>
	</PRODUCT>
	<PRODUCT PID="P002" CATEGORY="Consumer Durable">
		<NAME>Washing Machine</NAME>
		<DESCRIPTION>LG front load washining machine</DESCRIPTION>
		<PRICE>40000</PRICE>
	</PRODUCT>
	<PRODUCT PID="P003" CATEGORY="Accessories">
		<NAME>Ear phone</NAME>
		<DESCRIPTION>Samsung ear phone</DESCRIPTION>
		<PRICE>300</PRICE>
	</PRODUCT>
</PRODUCTS>

